{% set version = "1.1.0" %}

package:
  name: kisn-pylab
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/bartulem/KISN-PyLab.git

requirements:
  host:
    - python=3.6

  run:
    - python = 3.6
    - importlib-metadata >= 1.5.0	
    - ipykernel	>= 5.1.4	
    - ipython	>= 7.12.0	
    - ipython-genutils >= 0.2.0	
    - ipywidgets >= 7.5.1	
    - jedi >= 0.16.0	
    - json5 >= 0.9.1	
    - jsonschema >= 3.2.0	
    - jupyter >= 1.0.0	
    - jupyter-client >= 5.3.4	
    - jupyter-console >= 6.1.0	
    - jupyter-core >= 4.6.3	
    - jupyterlab >= 1.2.6	
    - jupyterlab-server >= 1.0.6	
    - matplotlib >= 3.1.3	
    - notebook >= 6.0.3	
    - numpy >= 1.18.1	
    - pandas >= 1.0.1	
    - pandocfilters >= 1.4.2	
    - pickleshare >= 0.7.5	
    - pip >= 20.0.2	
    - scipy >= 1.4.1	
    - setuptools >= 45.2.0.post20200210	
    - tqdm >= 4.42.1

test:
  imports:
    -

about:
  home: https://github.com/bartulem/KISN-PyLab
  license: GNU GENERAL PUBLIC LICENSE
  license_file: LICENSE
